import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "@/app/components/SideBar";
import SectionProgress from "./components/ScrollProgress";
import ScrollIndicator from "./components/ScrollProgress";
import { Tourney, Funnel_Display } from 'next/font/google'

const climateCrisis = Tourney({ 
  subsets: ['latin'],
  weight: '500', // Climate Crisis only has one weight (400)
  variable: '--font-climate-crisis',
})

const comicRelief = Funnel_Display({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-comic-relief',
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${climateCrisis.variable} ${comicRelief.variable}`}>
      <head>
        <link 
          rel="stylesheet" 
          type="text/css" 
          href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css" 
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen bg-white">
          <div className="lg:w-80">
            <SideBar />
          </div>

          <div className="flex-1 flex items-center justify-center bg-white">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}